/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TB_PenggajianKaryawan;

/**
 *
 * @author ASUS
 */
public class GUI_gajikrywn extends javax.swing.JFrame {

    /**
     * Creates new form GUI_gajikrywn
     */
    public GUI_gajikrywn() {
        initComponents();
        
        txtTotal.setEnabled(false);
        txtTotal.setText(String.valueOf(5500000));
    }
  //      Datagaji data = new Datagaji();
   //     data.gajisupervisor();
  //      data.totalgajisupervisor();
        
   //     data.gajimanager();
  //      data.totalgajimanager();
  //      data.tunjanganmanager();
  //      
   //     txtTotal.setEnabled(false);
  //      txtTunjangan.setEnabled(false);
   //     txtGaji.setEnabled(false);
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        cmb_pilih = new javax.swing.JComboBox();
        txtGaji = new javax.swing.JTextField();
        txtTunjangan = new javax.swing.JTextField();
        btn_cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        txtTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DATA GAJI KARYAWAN");

        jLabel2.setText("Nama ");

        jLabel3.setText("Jabatan");

        jLabel4.setText("Gaji");

        jLabel5.setText("Tunjangan");

        cmb_pilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Super Visor", " " }));
        cmb_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pilihActionPerformed(evt);
            }
        });

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        jLabel6.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_cetak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNama)
                                .addComponent(cmb_pilih, 0, 137, Short.MAX_VALUE)
                                .addComponent(txtGaji)
                                .addComponent(txtTunjangan)
                                .addComponent(txtTotal)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addComponent(btn_cetak)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        Hasil.setText("");
        
        Datagaji data = new Datagaji();
        
        data.nama = txtNama.getText();
        data.gaji = (Integer.parseInt(txtGaji.getText()));
        data.tunjangan = (Integer.parseInt(txtTunjangan.getText()));
        data.total = (Integer.parseInt(txtTotal.getText()));
        
        Hasil.append("Data Gaji Karyawan\n");
        if(cmb_pilih.getSelectedIndex() == 0){
             Hasil.append("Nama Manager \t : " + data.namamanager() + "\n");
             Hasil.append("Jabatan \t : " + data.jabatanmanager() + "\n");
             Hasil.append("Gaji Manager \t : Rp." + data.gajimanager() + "\n");
             Hasil.append("Tunjangan Manager \t : Rp." + data.tunjanganmanager() + "\n");
             Hasil.append("Gaji Akhir Manager \t : Rp." + data.totalmanager()+ "\n");
         }
        else if(cmb_pilih.getSelectedIndex() == 1){
             Hasil.append("Nama Super Visor \t : " + data.namasupervisor() + "\n");
             Hasil.append("Jabatan \t : " + data.jabatansupervisor() + "\n");
             Hasil.append("Gaji Super Visor \t : Rp." + data.gajisupervisor() + "\n");
             Hasil.append("Tunjangan Super Visor \t : Rp." + data.tunjangansupervisor() + "\n");
             Hasil.append("Gaji Akhir Super Visor \t : Rp." + data.totalsupervisor()+ "\n");
        }
        
 //       Datagaji data = new Datagaji();
 //        Hasil.setText("");
  //       data.nama = (txtNama.getText());
        
 //        Hasil.append("Data Gaji Karyawan\n");
 //        Hasil.append("Nama\t : " + data.nama + "\n");
        
  //       if(cmb_pilih.getSelectedIndex() == 0){
  //           int a;
  //           a = Integer.parseInt(txtGaji.getText());
  //           Hasil.append("Gaji \t : Rp." + data.gajisupervisor() + "\n");
  //           Hasil.append("Tunjangan \t : Rp." + data.tunjangansupervisor() + "\n");
  //           Hasil.append("Total : Rp." + data.totalgajisupervisor());
  //       }
  //       else if(cmb_pilih.getSelectedIndex() == 1){
  //           int a;
  //           a= Integer.parseInt(txtGaji.getText());
  //           Hasil.append("Gaji \t : Rp." + data.gajimanager() + "\n");
   //          Hasil.append("Tunjangan \t : Rp." + data.tunjanganmanager() + "\n");
   //          Hasil.append("Total : Rp." + data.totalgajimanager());
   //      }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void cmb_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pilihActionPerformed
        // TODO add your handling code here:
        Datagaji data = new Datagaji();
        if(cmb_pilih.getSelectedIndex()== 0){
            txtNama.setText(String.valueOf(data.namamanager()));
            txtGaji.setText(String.valueOf(data.gajimanager()));
            txtTunjangan.setText(String.valueOf(data.tunjanganmanager()));
        }
        else if(cmb_pilih.getSelectedIndex()== 1){
            txtNama.setText(String.valueOf(data.namasupervisor()));
            txtGaji.setText(String.valueOf(data.gajisupervisor()));
            txtTunjangan.setText(String.valueOf(data.tunjangansupervisor()));  
        }
        
        
  //      Datagaji data = new Datagaji();
  //      if(cmb_pilih.getSelectedIndex() == 0){
  //          txtGaji.setText(String.valueOf(data.gajisupervisor()));
  //          txtTotal.setText(String.valueOf(data.totalgajisupervisor()));
  //          txtTunjangan.setText(String.valueOf(data.tunjangansupervisor()));
  //      }
  //      else if(cmb_pilih.getSelectedIndex() == 1){
  //          txtGaji.setText(String.valueOf(data.gajimanager()));
  //          txtTotal.setText(String.valueOf(data.totalgajimanager()));
 //           txtTunjangan.setText(String.valueOf(data.tunjanganmanager()));  
 //       }
    }//GEN-LAST:event_cmb_pilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_gajikrywn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_gajikrywn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_gajikrywn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_gajikrywn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_gajikrywn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JComboBox cmb_pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTunjangan;
    // End of variables declaration//GEN-END:variables
}
